// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" };
import * as $0 from "./routes/[name]/index.tsx";
import * as $1 from "./routes/[name]/netflix.tsx";
import * as $2 from "./routes/[name]/watch.tsx";
import * as $3 from "./routes/index.tsx";
import * as $4 from "./routes/search.tsx";
import * as $5 from "./routes/u/[user]/index.tsx";
import * as $$0 from "./islands/KDramaSearch.tsx";

const manifest = {
  routes: {
    "./routes/[name]/index.tsx": $0,
    "./routes/[name]/netflix.tsx": $1,
    "./routes/[name]/watch.tsx": $2,
    "./routes/index.tsx": $3,
    "./routes/search.tsx": $4,
    "./routes/u/[user]/index.tsx": $5,
  },
  islands: {
    "./islands/KDramaSearch.tsx": $$0,
  },
  baseUrl: import.meta.url,
  config,
};

export default manifest;
